<h2 align="center">Hi there<img src="https://fastly.jsdelivr.net/gh/CoolPlayLin/CoolPlayLin/Images/Hello.gif" height="32" />, I'm CoolPlayLin </h2>
<h3 align="center">A beginner in Chinese html</h3>

<!--
**CoolPlayLin/CoolPlayLin** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

-  ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
-  ...
- 💬 Ask me about ...
-  ...
-  ...
- ⚡ Fun fact: ...
-->
<img align="right" src="https://github-readme-stats.vercel.app/api?username=CoolPlayLin&theme=default&show_icons=true">

<ul>
    <li>😄 Pronouns:CoolCodes</li>
    <li>🔭 I’m currently working on How to set up a personal website.</li>
    <li>📫 How to reach me:My Email is <a style="color: rgb(0, 255, 34);" href="mailto:CoolPlayLin@foxmail.com">CoolPlayLin@foxmail.com</a></li>
</ul>
