name: Profile

on:
  schedule: [{ cron: 0 * * * * }]
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.classic.svg
          committer_token: ${{ secrets.COOLPLAYLIN_BOT_TOKEN }}
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
  snk:
    needs: [metrics]
    runs-on: ubuntu-latest
    if: false
    env:
      GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
    steps:
      - name: Setup Information
        run: |
          git config --global user.email 130831920+coolplaylinbot@users.noreply.github.com
          git config --global user.name coolplaylinbot
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          token: ${{ secrets.COOLPLAYLIN_BOT_TOKEN }}
      - name: Push to master
        run: |
          if [[ -n $(git status -s) ]]; then
          git add .
          git commit -m "Update SNK"
          git push origin master --force
          else
          echo "No Change, Bye bye!"
          fi
